Merge upstream/master into REQ-67
Fix Conflicts:
  XenAdmin/Commands/MigrateVitualDiskCommand.cs
  XenAdmin/Commands/MoveVirtualDiskCommand.cs
  XenAdmin/TabPages/SrStoragePage.cs
  XenModel/Messages.resx

Fix Compilation error:
  XenAdmin/Commands/DisableChangedBlockTrackingCommand.cs
  XenModel/Actions/VDI/VDIDisableCbtAction.cs

Signed-off-by: Ji Jiang <ji.jiang@citrix.com>